version: "3.1"
services:
  backend:
    image: ums/backend
    container_name: ums_backend
    network_mode: host
    restart: always
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file: ./backend/.env
  db:
    image: ums/postgres
    container_name: ums_db
    network_mode: host
    restart: always
    build: ./backend/src/db
    ports:
      - 5432:5432

  frontend:
    image: ums/frontend
    container_name: ums_frontend
    network_mode: host
    restart: always
    build: ./frontend
    ports: 
      - '5173:5173'
