version: "3.1"
services:
  backend:
    image: ums/backend
    container_name: ums_backend
    restart: always
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: ums/postgres
    container_name: ums_db
    network_mode: host
    restart: always
    build: ./src/db
    ports:
      - 5432:5432
